##
#  deploy for spring development
#  docker-compose up -d

version: '3.1'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.1.0
    restart: unless-stopped

    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./realm/:/config/
      - ./realm/theme/:/opt/jboss/keycloak/themes/onenet-theme
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - DB_VENDOR=postgres
      - DB_USER=${KEYCLOAK_DATABASE_USERNAME}
      - DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT}:${KEYCLOAK_INTERNAL_PORT}"
    depends_on:
      - keycloak-db
    networks:
      - common


  keycloak-db:
    container_name: keycloak-db
    image: postgres:10
    environment:
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      POSTGRES_DB: keycloakdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - common

volumes:
  pgdata:

networks:
  common:
    driver: bridge
